### ISSUE TITLE
[BUG] Movecraft Stairs/Slabs

### ISSUE THREAD

**Issue by JensenJ** [JensenJ/EmbargoMC-IssueTracker#32]
**Describe the bug**
Stairs and slabs prevent Movecraft ships from functioning correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add slabs or stairs to Movecraft vehicle.
2. Try to move
3. See error

**Expected behaviour**
Slabs and stairs to work correctly on Movecraft vehicles.

**Additional Context**
May only happen with non-oak wood types.

**Comment by NoahSlocombe** [comment]
Found the stairs that don't work with movecraft:

STAIRS
Crimson
Acacia
Dark prismerine
Dark oak
Purpur
Cobble
Brick
Sandstone
Prismerine
Priserine Brick
Warped Stairs
Red Sandstone
Polished Granite
Smooth red sandstone
Smooth sandstone
Stone
End brick
Mossy Cobblestone
Polished Diorite
Mossy stone brick
Polished Blackstone Brick
Polished Blackstone
Diorite
Polished andersite
Red nether brick
andersite
grinite
smooth quartz

ALL SLABS WORK
